---
name: "MediaTracker"
guid: "4e47221f-3a04-42ab-90c6-d458d6509b30"
version: "2.0.0.3"
targetAbi: "10.9.1.0"
framework: "net8.0"
overview: "MediaTracker scrobbler"
description: "MediaTracker scrobbler. EXPERIMENTAL CHANGES!!!"
category: "General"
owner: "fluffy-godzilla"
artifacts:
  - "Jellyfin.Plugin.MediaTracker.dll"
changelog: |-
  - "Added a lock that protects ShouldSkipAction and CanMarkAsSeen"
